/* Ella Content Workbook — slot data.
   Each section maps to a place on the site. Each slot has:
   id      stable key (used to save your words locally)
   label   what this piece of text is
   guide   how long + what tone (a guide, not a rule)
   current the placeholder that's on the site right now (reference only)
   long    true → big multi-line field
   flag    optional banner: 'source' (needs a citation) | 'real' (must be real, not invented) | 'scope' (pending the menopause-vs-wellness decision)
*/
window.WORKBOOK = [
  {
    page: 'Global (appears on every page)',
    blurb: 'The little persistent bits — the top strip, the footer, the newsletter.',
    slots: [
      { id: 'promo', label: 'Rotating top strip', long: true,
        guide: '4 short nudges, ~5–9 words each, each ending in an action. These rotate at the very top of every page.',
        current: 'New: Free doctor-visit checklist (PDF)\nGet Jessica\u2019s weekly note in your inbox\nTake the 5-question check-in\nAvailable in English / Espa\u00f1ol' },
      { id: 'footer_tagline', label: 'Footer tagline',
        guide: 'One warm line, ~8–14 words. Your mission in a single breath.',
        current: 'Women supporting women through every hormonal stage of life.' },
      { id: 'newsletter', label: 'Newsletter block (title · subtitle · button)', long: true,
        guide: 'Title ~3–5 words, subtitle ~4–8 words, button 1–2 words. This is your main list-building moment.',
        current: 'Get the weekly note.\nHonest, useful, never spammy.\nSubscribe' },
    ],
  },
  {
    page: 'Homepage — Hero',
    blurb: 'The first screen. ~90% of the decision to stay happens here. Every word earns its place.',
    slots: [
      { id: 'hero_eyebrow', label: 'Eyebrow (tiny label above the headline)',
        guide: '2–4 words, ALL CAPS. Your positioning in a breath. (Currently "BY WOMEN, FOR WOMEN".)',
        current: 'BY WOMEN, FOR WOMEN' },
      { id: 'hero_h1', label: 'Main headline',
        guide: '3–6 words. The emotional hook — what she feels, not what you sell. One word can be italic for emphasis.',
        current: 'You\u2019re not imagining it.' },
      { id: 'hero_sub', label: 'Sub-headline',
        guide: '1–2 sentences, ~25–40 words. What Ella is + who it\u2019s for. Plain, calm, specific.',
        current: 'Honest, plainspoken information about menopause, nutrition, supplements, exercise, mental health, and the questions to ask your doctor. Built by a physician assistant for women who deserve answers.' },
      { id: 'hero_afford', label: 'Affordability line (the highlighted quote)',
        guide: '1 sentence. The accessibility promise.',
        current: 'Everything you need to know about menopause without breaking the bank. Built to be affordable and accessible.' },
      { id: 'hero_ctas', label: 'The two buttons',
        guide: 'Two labels, 1–3 words each. One primary action, one softer.',
        current: 'Start reading  /  Meet Jessica' },
      { id: 'hero_cred', label: 'Credential line (under the buttons)', flag: 'source',
        guide: 'Factual, verifiable credentials only. This is the trust anchor — keep it true.',
        current: 'Jessica Zavala, PA-C · OB-GYN background · Women\u2019s wellness certificate' },
    ],
  },
  {
    page: 'Homepage — Why this matters',
    blurb: 'The "why should I care" section. Sets the stakes for menopause specifically.',
    slots: [
      { id: 'why_eyebrow', label: 'Eyebrow', guide: '2–4 words, caps.', current: 'WHY THIS MATTERS' },
      { id: 'why_h2', label: 'Section headline',
        guide: '1 line, can wrap to two. A reframe or a truth. Italic emphasis allowed.',
        current: 'Menopause isn\u2019t the end of anything. It just doesn\u2019t get talked about.' },
      { id: 'why_p1', label: 'Paragraph 1', long: true, flag: 'source',
        guide: '~40–60 words. The problem. Any statistic here needs a source (see the Sources page).',
        current: 'About half of all women will go through menopause — and yet most medical curricula spend less than an hour on it. The result: millions of women navigate a decade of hormonal change with almost no real guidance.' },
      { id: 'why_p2', label: 'Paragraph 2', long: true,
        guide: '~40–60 words. The turn toward hope / agency. End on what Ella does.',
        current: 'Knowing what\u2019s happening, what\u2019s worth doing about it, and what questions to ask your doctor — that\u2019s the difference between feeling lost and feeling in charge. Ella is for the second one.' },
      { id: 'why_stats', label: 'Two stats', long: true, flag: 'source',
        guide: 'Two punchy numbers + labels. EACH NEEDS A SOURCE. Replace with stats you can stand behind.',
        current: '7–14 yrs — Average length of perimenopause\nless than 1 hour — Typical medical-school coverage of menopause' },
    ],
  },
  {
    page: 'Homepage — What we cover (the 6 pillars)',
    blurb: 'The content map. If Ella becomes menopause-only, some of these get reframed or cut (see your Q1 decision).',
    slots: [
      { id: 'pillars_eyebrow', label: 'Eyebrow', guide: '2–4 words, caps.', current: 'WHAT WE COVER' },
      { id: 'pillars_h2', label: 'Section headline', guide: '1 short line.', current: 'Everything in one trusted place.' },
      { id: 'pillar_nutrition', label: 'Pillar 1 — Nutrition (title + 1 line)',
        guide: 'Title 1–2 words, description ~12–18 words. Frame it through the menopause lens.',
        current: 'Nutrition — Foods to include, protein needs during menopause, healthier swaps. No meal plans, just real information.' },
      { id: 'pillar_supplements', label: 'Pillar 2 — Supplements (title + 1 line)', flag: 'scope',
        guide: 'Same shape. Note: this is the most likely future revenue area — keep it honest, "what\u2019s worth it" not "buy this".',
        current: 'Supplements — Omega-3, Vit D, Vit K, collagen, magnesium glycinate, fiber. What\u2019s worth taking, with links to buy.' },
      { id: 'pillar_exercise', label: 'Pillar 3 — Exercise (title + 1 line)',
        guide: 'Same shape.',
        current: 'Exercise — Strength training, walking, yoga. Light weights count. Less cardio, more muscle.' },
      { id: 'pillar_mental', label: 'Pillar 4 — Mental health (title + 1 line)',
        guide: 'Same shape.',
        current: 'Mental health — Support groups, meetups, resource links. You\u2019re not alone, and the data backs that up.' },
      { id: 'pillar_skin', label: 'Pillar 5 — Skin care (title + 1 line)', flag: 'scope',
        guide: 'Pending Q1: if Ella is menopause-only, this may get cut or folded into another pillar.',
        current: 'Skin care — What hormonal changes do to your skin, and what actually helps.' },
      { id: 'pillar_hormones', label: 'Pillar 6 — Hormonal therapy (title + 1 line)',
        guide: 'Same shape. Keep the "options, not endorsements" stance.',
        current: 'Hormonal therapy — HRT options explained in plain English. No endorsements, just clarity.' },
    ],
  },
  {
    page: 'Homepage — Check-in banner',
    blurb: 'Invites her into the quiz.',
    slots: [
      { id: 'checkin_eyebrow', label: 'Eyebrow', guide: '2–3 words, caps.', current: 'PERSONAL CHECK-IN' },
      { id: 'checkin_h2', label: 'Headline', guide: 'A question or invitation, ~3–6 words.', current: 'Not sure where to start?' },
      { id: 'checkin_p', label: 'Paragraph', long: true,
        guide: '~20–30 words. What the quiz does and why it\u2019s safe (no score, no judgment).',
        current: 'Answer a few quick questions and we\u2019ll point you to the right reading, based on what you\u2019re actually experiencing.' },
      { id: 'checkin_btn', label: 'Button label', guide: '2–4 words.', current: 'Take the check-in' },
    ],
  },
  {
    page: 'Homepage — Work with Jessica (consultation)',
    blurb: 'The soft sell: a 15-minute call. Keep low-pressure.',
    slots: [
      { id: 'consult_eyebrow', label: 'Eyebrow', guide: '2–3 words, caps.', current: 'WORK WITH ME' },
      { id: 'consult_h2', label: 'Headline', guide: '~4–8 words. Name the offer plainly.', current: 'Book a 15-minute wellness consultation.' },
      { id: 'consult_p', label: 'Paragraph', long: true,
        guide: '~30–45 words. What the call is, what it isn\u2019t. No pressure.',
        current: 'A short, no-pressure call with Jessica to talk through your symptoms, your questions, and where to go next. No commitment, just clarity.' },
      { id: 'consult_list', label: 'Three bullet points', long: true,
        guide: 'Three short outcomes, ~4–7 words each.',
        current: 'Personalized guidance for your stage\nWhat to ask your own doctor\nWhere to start, without the overwhelm' },
    ],
  },
  {
    page: 'Homepage — Testimonials',
    blurb: 'Social proof. These build or break trust instantly.',
    slots: [
      { id: 'testi_eyebrow', label: 'Eyebrow', guide: '2–5 words, caps.', current: 'IN THEIR OWN WORDS' },
      { id: 'testi_h2', label: 'Headline', guide: '~2–4 words.', current: 'Feeling seen, finally.' },
      { id: 'testi_quotes', label: 'The quotes', long: true, flag: 'real',
        guide: 'These are INVENTED right now. Use only REAL quotes (with permission). One per line: "quote" — First name L., age. Start with 2–3 real ones; better few-and-true than many-and-fake.',
        current: '"For the first time I feel like I have real information." — Marta R., 52\n"I brought the list to my OB-GYN and we had a real conversation." — Elena G., 48\n"Having it in Spanish makes all the difference." — Carolina M., 50\n"I didn\u2019t feel judged. I felt heard." — Patricia D., 55\n"The check-in helped me understand where I am." — Lorena S., 46' },
    ],
  },
  {
    page: 'Homepage — Everything you need (link grid)',
    blurb: 'The closing directory of quick jumps. Pure navigation.',
    slots: [
      { id: 'info_eyebrow', label: 'Eyebrow', guide: '2–4 words, caps.', current: 'EVERYTHING YOU NEED' },
      { id: 'info_h2', label: 'Headline', guide: '~3–5 words.', current: 'The information you need.' },
      { id: 'info_cols', label: 'Three columns (title + link labels)', long: true,
        guide: 'Three groupings, each a title + 4–5 link labels. These should mirror your real sections.',
        current: 'Nutrition & exercise: Protein after 45 · Healthier swaps · Strength training for beginners · Yoga for mental health\nPeri/Menopause: Hormonal therapy options · OB-GYN visit checklist · Find a specialist · Supplements to know\nReproductive health: HPV, what to know · Screening schedule · Symptoms not to brush off · Skin care and hormones' },
    ],
  },
  {
    page: 'The Check-in Quiz',
    blurb: '5 questions → a personalized reading list. Tone: gentle, no score, no diagnosis.',
    slots: [
      { id: 'quiz_intro', label: 'Quiz intro (title + subtitle)', long: true,
        guide: 'Title ~4–6 words, subtitle ~15–25 words. Reassure: short, no judgment.',
        current: 'A short, gentle check-in.\nFive quick questions. No score, no judgment, just a clearer picture of what stage your body is in and what to read next.' },
      { id: 'quiz_q1', label: 'Q1 — Stage (question + 5 options)', long: true,
        guide: 'Question + 5 options, one per line. Keep it kind and uncertain-friendly.',
        current: 'Where are you in your journey?\n• My periods are still regular\n• My periods are changing or irregular\n• It\u2019s been 12+ months since my last period\n• I\u2019ve had surgical or medical menopause\n• I\u2019m not sure where I am' },
      { id: 'quiz_q2', label: 'Q2 — Symptoms (question + 8 options, multi-select)', long: true,
        guide: 'Question + up to 8 options + a "none" option. One per line.',
        current: 'Which of these have you noticed lately?\n• Hot flashes or night sweats\n• Sleep changes or insomnia\n• Mood shifts, anxiety, or low mood\n• Brain fog or memory lapses\n• Irregular or heavy periods\n• Vaginal dryness or changes in libido\n• Joint aches or weight changes\n• None of these right now' },
      { id: 'quiz_q3', label: 'Q3 — Daily impact (question + 4 options)', long: true,
        guide: 'Question + 4 options.',
        current: 'How much is this affecting your daily life?\n• Barely, I\u2019m mostly curious\n• Some days are harder than others\n• A lot, it\u2019s hard to ignore\n• I\u2019m honestly not sure' },
      { id: 'quiz_q4', label: 'Q4 — Goals (question + 6 options, multi-select)', long: true,
        guide: 'Question + 6 options.',
        current: 'What would feel most helpful right now?\n• Understanding what\u2019s happening to my body\n• Nutrition and exercise that fit this stage\n• Knowing which supplements are worth it\n• Learning about hormone therapy options\n• Knowing what to ask my doctor\n• Feeling less alone in it' },
      { id: 'quiz_q5', label: 'Q5 — Doctor history (question + 4 options)', long: true,
        guide: 'Question + 4 options.',
        current: 'Have you talked to a doctor about this?\n• Yes, and it was helpful\n• Yes, but I felt dismissed\n• Not yet\n• No, I\u2019m not sure how to bring it up' },
      { id: 'quiz_result', label: 'Results headline + disclaimer', long: true, flag: 'source',
        guide: 'Headline ~5–8 words. Keep the medical disclaimer (general info, not advice).',
        current: 'Here\u2019s a starting place, just for you.\n[Disclaimer] This is general information, not medical advice or a diagnosis. For your specific situation, talk with your own doctor.' },
    ],
  },
  {
    page: 'About Jessica',
    blurb: 'The founder page. For this audience, this page is the trust engine. Write it in first person.',
    slots: [
      { id: 'about_eyebrow', label: 'Eyebrow', guide: '2–4 words, caps.', current: 'MEET THE FOUNDER' },
      { id: 'about_h1', label: 'Headline', guide: 'A warm hello, ~2–4 words.', current: 'Hi, I\u2019m Jessica.' },
      { id: 'about_lede', label: 'Opening paragraph', long: true,
        guide: '~40–60 words. Who you are + the moment that made you build Ella.',
        current: 'I\u2019m a physician assistant with an OB-GYN background. I built Ella because, over and over, I watched women in their forties and fifties walk into the clinic exhausted, scared, and without answers. You shouldn\u2019t have to piece this together alone.' },
      { id: 'about_creds', label: 'Credentials (list)', long: true, flag: 'source',
        guide: 'Real, verifiable credentials only. One per line.',
        current: 'Physician Assistant, Certified (PA-C)\nClinical training in obstetrics and gynecology\nWomen\u2019s Wellness certificate\nYears of personal research in women\u2019s hormonal health' },
      { id: 'about_why', label: '"Why Ella" paragraph', long: true, flag: 'source',
        guide: '~40–60 words. The gap Ella fills. (Stat about med-school coverage needs a source.)',
        current: 'Most medical curricula spend under an hour on menopause. That means millions of women are navigating a decade of hormonal change with almost no guidance. That gap is exactly why Ella exists.' },
      { id: 'about_promise', label: 'Your promise (pull-quote)', long: true,
        guide: '1 sentence, quotable. Your core stance.',
        current: 'My promise is simple: honest information, no alarmism, no selling you anything you don\u2019t need.' },
      { id: 'about_isnt', label: '"What Ella isn\u2019t" paragraph', long: true,
        guide: '~30–45 words. Sets boundaries: not a doctor, no diagnosis, no endorsements.',
        current: 'Ella doesn\u2019t replace your doctor. It doesn\u2019t diagnose. It doesn\u2019t endorse any specific brand, hormone protocol, or therapy. What it does: help you understand your options and walk into your next appointment with the right questions.' },
      { id: 'about_contact', label: 'Contact line + email', flag: 'real',
        guide: 'One line + a real email address.',
        current: 'Question, idea, or collaboration? Reach me at jessica@ellahealth.com' },
    ],
  },
  {
    page: 'Articles (6)',
    blurb: 'Each article = a title, a one-line lede, and the body. Rewrite the body in your voice — aim for ~4–8 short sections with one pull-quote. Any number/claim needs a source.',
    slots: [
      { id: 'art_protein', label: 'Article — Protein after 45 (Nutrition)', long: true, flag: 'source',
        guide: 'Title + lede + body. Current sections: How much do you need · Foods to add this week. The protein numbers need sources.',
        current: 'Title: Protein after 45: why it suddenly matters so much.\nLede: Your body starts losing muscle faster than before, and protein is the single most useful tool to slow it down.' },
      { id: 'art_peri', label: 'Article — What is perimenopause (Perimenopause)', long: true, flag: 'source',
        guide: 'Title + lede + body. Current sections: The hormone shift in plain English · Common signs.',
        current: 'Title: What is perimenopause, really?\nLede: The years before menopause are often the loudest. Here\u2019s what\u2019s actually happening, when it usually starts, and what to expect.' },
      { id: 'art_swaps', label: 'Article — Five food swaps (Nutrition)', long: true,
        guide: 'Title + lede + body. List of 5 swaps.',
        current: 'Title: Five food swaps your hormones will thank you for.\nLede: Small changes, not a meal plan. Five swaps that nudge your nutrition in the right direction.' },
      { id: 'art_sleep', label: 'Article — Sleep & hormones (Mental health)', long: true, flag: 'source',
        guide: 'Title + lede + body. Keep claims sourced.',
        current: 'Title: Sleep, hormones, and what actually helps.\nLede: Sleep changes in perimenopause are real, frustrating, and fixable.' },
      { id: 'art_strength', label: 'Article — Strength training for beginners (Exercise)', long: true,
        guide: 'Title + lede + body.',
        current: 'Title: Strength training when you\u2019ve never lifted before.\nLede: You don\u2019t need a gym, a coach, or any equipment to start.' },
      { id: 'art_hotflash', label: 'Article — The truth about hot flashes (Perimenopause)', long: true, flag: 'source',
        guide: 'Title + lede + body.',
        current: 'Title: The truth about hot flashes.\nLede: Why they happen, why they feel different at 3 a.m., and the surprisingly long menu of things that help.' },
    ],
  },
  {
    page: 'Other pages (longer — outline these)',
    blurb: 'These hold more content. For now, give me the headline + the list of items/sections you want; we\u2019ll draft the bodies together.',
    slots: [
      { id: 'sec_supplements', label: 'Supplements hub', long: true, flag: 'scope',
        guide: 'Intro headline + which supplements to feature + your stance on each. (Future revenue area — keep it "what\u2019s worth it".)',
        current: 'Currently lists: Omega-3, Vitamin D, Vitamin K, collagen, magnesium glycinate, fiber — each with a "why", dosing notes, and research backing.' },
      { id: 'sec_hormones', label: 'Hormonal therapy page', long: true, flag: 'source',
        guide: 'Intro headline + the options you want to explain. Keep "options, not endorsements". Link authoritative sources.',
        current: 'Currently: explains HRT options + external links, framed as options-only, never endorsing.' },
      { id: 'sec_doctor', label: 'Doctor-visit checklist (printable)', long: true,
        guide: 'The actual questions you want women to bring to their OB-GYN. This is a flagship freebie — make it genuinely useful.',
        current: 'Currently: a printable/downloadable list covering perimenopause, HRT options, and finding a menopause specialist.' },
      { id: 'sec_cancer', label: 'Cancer & HPV page', long: true, flag: 'scope',
        guide: 'PENDING your Q1 scope call. If Ella stays menopause-only, this likely gets cut or folded into a single "screenings still matter" article.',
        current: 'Currently: a full screen on reproductive cancers, HPV, screening, and where to learn more.' },
    ],
  },
];
