// Article data store, 6 sample articles spanning Ella's content pillars.
// Each article has: id, category, tone, title, lede, readTime, body (array of
// block objects). Bilingual via lang parameter.
//
// Body block kinds:
//   { kind: 'p',    text }
//   { kind: 'h2',   text }
//   { kind: 'pull', text }
//   { kind: 'ul',   items: [...] }
//   { kind: 'table', headers: [...], rows: [[...], ...] }

export const ELLA_ARTICLES = {
  en: [
    {
      id: 'protein-after-45',
      category: 'Nutrition',
      tone: 'sage',
      title: 'Protein after 45: why it suddenly matters so much.',
      lede: 'Your body starts losing muscle faster than before, and protein is the single most useful tool to slow it down. Here’s what you actually need.',
      readTime: '8 min read',
      published: 'March 2026',
      body: [
        { kind: 'p', text: 'If you’re entering perimenopause and your body suddenly feels like it isn’t the same, you’re not imagining it. After 45, we lose muscle faster, about 1% a year. The good news: protein works, and it works pretty quickly.' },
        { kind: 'pull', text: '“Aim for 1.2–1.6 grams of protein per kilo of body weight a day. For most women, that means rethinking breakfast first.”' },
        { kind: 'h2', text: 'How much do you actually need?' },
        { kind: 'p', text: 'The old guideline (the RDA of 0.8 g/kg) was set to prevent deficiency, not to preserve muscle through hormonal transition. Newer research suggests roughly double that.' },
        { kind: 'table',
          headers: ['Your weight', 'Floor', 'Target'],
          rows: [['55 kg / 121 lb','66 g','88 g'],['65 kg / 143 lb','78 g','104 g'],['75 kg / 165 lb','90 g','120 g'],['85 kg / 187 lb','102 g','136 g']] },
        { kind: 'h2', text: 'Foods to add this week' },
        { kind: 'p', text: 'We’re not building a meal plan here, just giving you the building blocks. Aim for 25–30 g of protein per meal. Easiest wins:' },
        { kind: 'ul', items: [
          'Greek yogurt (plain), 17 g per cup',
          'Eggs, 6 g each',
          'Chicken breast, 31 g per 100 g',
          'Cooked lentils, 18 g per cup',
          'Cottage cheese, 25 g per cup',
          'Firm tofu, 20 g per 100 g',
        ]},
      ],
    },
    {
      id: 'what-is-perimenopause',
      category: 'Perimenopause',
      tone: 'rose',
      title: 'What is perimenopause, really?',
      lede: 'The years before menopause are often the loudest. Here’s what’s actually happening, when it usually starts, and what to expect.',
      readTime: '6 min read',
      published: 'March 2026',
      body: [
        { kind: 'p', text: 'Perimenopause is the transition leading up to menopause, the years when your hormones start swinging unpredictably. It usually begins in your 40s but can start in your late 30s, and lasts anywhere from 4 to 10 years on average.' },
        { kind: 'h2', text: 'The hormone shift in plain English' },
        { kind: 'p', text: 'Estrogen doesn’t fall steadily, it spikes and dips. Progesterone drops more steadily. That mismatch is what causes most of the symptoms women report: heavy periods, mood shifts, sleep changes, brain fog, hot flashes, and joint aches.' },
        { kind: 'pull', text: '“If your symptoms feel ‘out of nowhere’ in your 40s, perimenopause is the most likely answer, even if your periods are still regular.”' },
        { kind: 'h2', text: 'Common signs (you don’t need all of them)' },
        { kind: 'ul', items: [
          'Periods that get heavier, lighter, closer together, or further apart',
          'Hot flashes or night sweats',
          'Sleep that’s suddenly different',
          'Mood shifts, anxiety, or low mood',
          'Brain fog or memory lapses',
          'Joint stiffness, especially mornings',
          'Lower libido',
        ]},
        { kind: 'h2', text: 'Menopause vs. perimenopause' },
        { kind: 'p', text: 'Menopause is officially diagnosed after 12 consecutive months without a period. Everything before that, even if you’re having symptoms, is perimenopause. Most women spend more time in perimenopause than they realize.' },
      ],
    },
    {
      id: 'foods-to-avoid',
      category: 'Nutrition',
      tone: 'sage',
      title: 'Foods to avoid, and why.',
      lede: 'No food is forbidden. But a few things tend to make perimenopause symptoms louder. Here are the ones worth cutting back on, and what changes when you do.',
      readTime: '5 min read',
      published: 'February 2026',
      body: [
        { kind: 'p', text: 'A reminder: Ella doesn’t do rules or guilt. This isn’t a list of things you can never eat again. It’s a short, honest look at the foods that most often worsen hot flashes, sleep, and energy in midlife, so you can choose what’s worth it.' },
        { kind: 'h2', text: '1. Alcohol' },
        { kind: 'p', text: 'It’s the single biggest sleep disruptor for women 45+, and a common hot-flash trigger. You don’t have to quit, but notice how a glass of red wine affects your night.' },
        { kind: 'h2', text: '2. Added sugar and refined carbs' },
        { kind: 'p', text: 'White bread, pastries, and sugary drinks spike your blood sugar and then drop it, which can feed energy crashes and mood swings. The fix isn’t zero sugar, it’s less of it and more fiber alongside.' },
        { kind: 'h2', text: '3. Too much caffeine' },
        { kind: 'p', text: 'Caffeine can intensify hot flashes and linger in your system longer than it used to. If sleep is rough, try a noon cutoff before anything else.' },
        { kind: 'h2', text: '4. Ultra-processed and fried foods' },
        { kind: 'p', text: 'High in inflammatory oils and sodium, low in the fiber and protein your body needs more of now. The occasional fry is fine, the everyday habit is what adds up.' },
        { kind: 'h2', text: '5. Very spicy food and piping-hot drinks' },
        { kind: 'p', text: 'Both can set off a hot flash by raising your core temperature. If you’re flashing a lot, these are easy, temporary things to dial back and test.' },
        { kind: 'pull', text: '“This isn’t about restriction. It’s about noticing which foods cost you a good night’s sleep, and deciding for yourself.”' },
      ],
    },
    {
      id: 'sleep-hormones',
      category: 'Mental Health',
      tone: 'plum',
      title: 'Sleep, hormones, and what actually helps.',
      lede: 'Sleep changes in perimenopause are real, frustrating, and fixable. Here’s what’s happening and what’s worth trying.',
      readTime: '7 min read',
      published: 'February 2026',
      body: [
        { kind: 'p', text: 'You’re waking up at 3 a.m. and can’t fall back asleep. Or you’re tired but wired. Or you wake up soaked. None of this is your imagination, it’s your hormones.' },
        { kind: 'h2', text: 'Why sleep gets weird now' },
        { kind: 'p', text: 'Progesterone has a calming, sleep-promoting effect, and it drops first in perimenopause. Estrogen affects body temperature, which is why night sweats wake you up. Cortisol rhythms also shift. All of this stacks.' },
        { kind: 'h2', text: 'What actually helps' },
        { kind: 'ul', items: [
          'Magnesium glycinate, 200–400 mg, 30 min before bed',
          'A cool room, 65–68°F / 18–20°C is the sweet spot',
          'Caffeine cutoff by noon, not 3 p.m.',
          'Alcohol is the single biggest sleep disruptor for women 45+',
          'Strength training earlier in the day improves sleep depth',
        ]},
        { kind: 'pull', text: '“Alcohol is the single biggest sleep disruptor for women in midlife. Cutting it for two weeks is the fastest experiment you can run.”' },
        { kind: 'h2', text: 'When to ask your doctor' },
        { kind: 'p', text: 'If sleep has been bad for more than 3 months and the basics haven’t helped, talk to your doctor about hormone therapy, low-dose estrogen, or non-hormonal options. You don’t have to white-knuckle it.' },
      ],
    },
    {
      id: 'strength-beginners',
      category: 'Exercise',
      tone: 'sage',
      title: 'Strength training when you’ve never lifted before.',
      lede: 'You don’t need a gym, a coach, or any equipment to start. Here’s a beginner-friendly path that actually works.',
      readTime: '6 min read',
      published: 'January 2026',
      body: [
        { kind: 'p', text: 'Strength training is the highest-leverage thing you can do for your body after 45. It protects bone, builds muscle, improves sleep, and helps insulin work better. And you can absolutely start at zero.' },
        { kind: 'h2', text: 'A two-week starter plan' },
        { kind: 'ul', items: [
          'Day 1: 10 squats, 10 wall push-ups, 10-second plank. Two rounds.',
          'Day 2: Walk 20 minutes.',
          'Day 3: Same as Day 1, add one more round.',
          'Day 4: Rest or walk.',
          'Day 5: Add 5 lb dumbbells (or two cans of beans) to your squats.',
          'Day 6–7: Repeat what feels good.',
        ]},
        { kind: 'h2', text: 'What “light weights” really means' },
        { kind: 'p', text: 'Light is a relative word. For someone who’s never lifted, 5 lb dumbbells are perfect. The point isn’t the weight, it’s the consistency. Two short sessions a week, every week, beats one heroic gym day a month.' },
        { kind: 'pull', text: '“Two short sessions a week, every week, beats one heroic gym day a month.”' },
      ],
    },
    {
      id: 'life-after-menopause',
      category: 'Menopause',
      tone: 'plum',
      title: 'Life after menopause: what changes, and what doesn’t.',
      lede: 'Menopause is a single day, twelve months after your last period. Everything after that is its own long chapter. Here’s what actually shifts.',
      readTime: '6 min read',
      published: 'March 2026',
      body: [
        { kind: 'p', text: 'Once you’re postmenopausal, the wild hormone swings of perimenopause settle into something steadier, low and stable. For many women, that alone brings relief: fewer surprises, more predictability.' },
        { kind: 'h2', text: 'What tends to ease up' },
        { kind: 'ul', items: [
          'Periods, obviously, are done',
          'Mood swings often stabilize once hormones stop fluctuating',
          'Hot flashes fade for most women within a few years, though not all',
        ]},
        { kind: 'h2', text: 'What deserves ongoing attention' },
        { kind: 'p', text: 'Lower estrogen long-term affects bone density, heart health, and vaginal tissue. None of this is scary, it’s just worth knowing so you can stay ahead of it with your doctor: bone density screening, cardiovascular checkups, and options for vaginal dryness if it comes up.' },
        { kind: 'h2', text: 'Early or surgical menopause' },
        { kind: 'p', text: 'If menopause happened earlier than expected, before 45, or suddenly through surgery, the same long-term considerations apply sooner. It’s worth an honest conversation with your doctor about hormone therapy given the longer stretch of time involved.' },
        { kind: 'pull', text: '“Menopause isn’t an ending. It’s a steadier chapter, and one worth knowing how to take care of.”' },
      ],
    },
    {
      id: 'intimacy-and-connection',
      category: 'Mental Health',
      tone: 'plum',
      title: 'Intimacy and connection through the change.',
      lede: 'Desire, dryness, and closeness with a partner all shift during this transition. None of it is shameful, and most of it is workable.',
      readTime: '6 min read',
      published: 'February 2026',
      body: [
        { kind: 'p', text: 'Lower estrogen thins and dries vaginal tissue, which can make sex uncomfortable or even painful. Lower testosterone and the general fatigue of this stage can lower desire too. Both are common, and neither has to be permanent.' },
        { kind: 'h2', text: 'What helps with dryness and discomfort' },
        { kind: 'ul', items: [
          'Vaginal moisturizers (used regularly, not just before sex)',
          'Silicone or water-based lubricant during intimacy',
          'Low-dose vaginal estrogen, ask your doctor, it’s different from systemic HRT',
          'Longer foreplay and unhurried pacing, arousal often takes more time now',
        ]},
        { kind: 'h2', text: 'The emotional side' },
        { kind: 'p', text: 'A dip in desire isn’t a verdict on your relationship or your body. Talking about it, with a partner or a doctor, tends to help more than staying quiet about it. Many women find that connection deepens once the conversation is out in the open.' },
        { kind: 'pull', text: '“You’re not broken, and you’re not alone. This is one of the most common, least talked-about parts of the transition.”' },
      ],
    },
    {
      id: 'hot-flashes',
      category: 'Menopause',
      tone: 'rose',
      title: 'The truth about hot flashes.',
      lede: 'Why they happen, why they feel different at 3 a.m., and the surprisingly long menu of things that help.',
      readTime: '5 min read',
      published: 'January 2026',
      body: [
        { kind: 'p', text: 'A hot flash is your brain misreading your body temperature. Estrogen fluctuation messes with the thermoregulation center in your hypothalamus. The result: your body thinks it’s overheating, opens the blood vessels near your skin, and tries to dump heat fast. That’s the flush.' },
        { kind: 'h2', text: 'Why night sweats feel worse' },
        { kind: 'p', text: 'At night, you’re horizontal, your blanket is on, and your body is in repair mode. A hot flash interrupts sleep and floods you with cortisol, which is why you can’t fall back asleep.' },
        { kind: 'h2', text: 'What’s worth trying' },
        { kind: 'ul', items: [
          'Layered clothing and a cool bedroom, obvious but real',
          'Avoid triggers: red wine, spicy food, very hot drinks',
          'Paced breathing (4 in, 6 out) at the first sign of a flush',
          'CBT for hot flashes has clinical support',
          'For severe symptoms, talk to your doctor about HRT or fezolinetant',
        ]},
        { kind: 'pull', text: '“If flashes are stealing your sleep or your sanity, you do not have to push through. There is a long menu of options.”' },
      ],
    },
  ],
  es: [
    {
      id: 'protein-after-45',
      category: 'Nutrición',
      tone: 'sage',
      title: 'Proteína después de los 45: por qué importa tanto.',
      lede: 'Tu cuerpo está perdiendo músculo más rápido que antes, y la proteína es la herramienta más útil para detenerlo. Esto es lo que realmente necesitas.',
      readTime: '8 min de lectura',
      published: 'Marzo 2026',
      body: [
        { kind: 'p', text: 'Si entras a la perimenopausia y de repente sientes que tu cuerpo no es el mismo, no te lo estás imaginando. Después de los 45, perdemos músculo más rápido, alrededor de 1% al año. La buena noticia: la proteína funciona, y funciona bastante rápido.' },
        { kind: 'pull', text: '«Apunta a 1.2–1.6 gramos de proteína por kilo de peso al día. Para la mayoría de mujeres, eso significa repensar el desayuno primero.»' },
        { kind: 'h2', text: '¿Cuánta necesitas, realmente?' },
        { kind: 'p', text: 'Las viejas pautas (la RDA de 0.8 g/kg) fueron creadas para evitar la deficiencia, no para mantener el músculo durante la transición hormonal. Investigación reciente sugiere casi el doble.' },
        { kind: 'table',
          headers: ['Tu peso', 'Mínimo', 'Objetivo'],
          rows: [['55 kg','66 g','88 g'],['65 kg','78 g','104 g'],['75 kg','90 g','120 g'],['85 kg','102 g','136 g']] },
        { kind: 'h2', text: 'Alimentos para incluir' },
        { kind: 'p', text: 'No estamos haciendo un plan de comidas, solo te damos los bloques. Apunta a 25–30 g de proteína por comida.' },
        { kind: 'ul', items: [
          'Yogur griego (puro), 17 g por taza',
          'Huevos, 6 g cada uno',
          'Pechuga de pollo, 31 g por 100 g',
          'Lentejas cocidas, 18 g por taza',
          'Requesón, 25 g por taza',
          'Tofu firme, 20 g por 100 g',
        ]},
      ],
    },
    {
      id: 'what-is-perimenopause',
      category: 'Perimenopausia',
      tone: 'rose',
      title: '¿Qué es la perimenopausia, en realidad?',
      lede: 'Los años antes de la menopausia suelen ser los más ruidosos. Esto es lo que está pasando, cuándo suele empezar, y qué esperar.',
      readTime: '6 min de lectura',
      published: 'Marzo 2026',
      body: [
        { kind: 'p', text: 'La perimenopausia es la transición hacia la menopausia, los años en que tus hormonas empiezan a moverse de forma impredecible. Suele comenzar en los 40, pero puede empezar a finales de los 30, y dura entre 4 y 10 años en promedio.' },
        { kind: 'h2', text: 'El cambio hormonal en lenguaje claro' },
        { kind: 'p', text: 'El estrógeno no baja de forma constante, sube y baja. La progesterona baja más establemente. Ese desajuste causa la mayoría de los síntomas: periodos abundantes, cambios de humor, problemas de sueño, niebla mental, sofocos y dolor articular.' },
        { kind: 'pull', text: '«Si tus síntomas aparecen "de la nada" en los 40, la perimenopausia es la respuesta más probable, aunque tus periodos sigan regulares.»' },
        { kind: 'h2', text: 'Signos comunes (no necesitas tenerlos todos)' },
        { kind: 'ul', items: [
          'Periodos más abundantes, más ligeros, más juntos o más separados',
          'Sofocos o sudores nocturnos',
          'Sueño que de repente es diferente',
          'Cambios de humor, ansiedad o tristeza',
          'Niebla mental o lapsos de memoria',
          'Rigidez articular, especialmente por la mañana',
          'Menos deseo sexual',
        ]},
      ],
    },
    {
      id: 'foods-to-avoid',
      category: 'Nutrición',
      tone: 'sage',
      title: 'Alimentos a evitar, y por qué.',
      lede: 'Ningún alimento está prohibido. Pero algunas cosas tienden a empeorar los síntomas de la perimenopausia. Estas son las que vale la pena reducir, y qué cambia cuando lo haces.',
      readTime: '5 min de lectura',
      published: 'Febrero 2026',
      body: [
        { kind: 'p', text: 'Un recordatorio: Ella no hace reglas ni culpa. Esto no es una lista de cosas que nunca podrás volver a comer. Es una mirada corta y honesta a los alimentos que con más frecuencia empeoran los sofocos, el sueño y la energía en la mediana edad, para que tú decidas qué vale la pena.' },
        { kind: 'h2', text: '1. Alcohol' },
        { kind: 'p', text: 'Es el mayor perturbador del sueño para mujeres de 45+, y un desencadenante común de sofocos. No tienes que dejarlo, pero nota cómo una copa de vino tinto afecta tu noche.' },
        { kind: 'h2', text: '2. Azúcar añadida y carbohidratos refinados' },
        { kind: 'p', text: 'El pan blanco, la repostería y las bebidas azucaradas suben tu azúcar en sangre y luego la bajan, lo que alimenta bajones de energía y cambios de humor. La solución no es cero azúcar, es menos y con más fibra al lado.' },
        { kind: 'h2', text: '3. Demasiada cafeína' },
        { kind: 'p', text: 'La cafeína puede intensificar los sofocos y quedarse en tu sistema más tiempo que antes. Si el sueño es difícil, prueba un límite al mediodía antes que nada.' },
        { kind: 'h2', text: '4. Alimentos ultraprocesados y fritos' },
        { kind: 'p', text: 'Altos en aceites inflamatorios y sodio, bajos en la fibra y proteína que tu cuerpo necesita más ahora. Una fritura ocasional está bien, el hábito diario es lo que suma.' },
        { kind: 'h2', text: '5. Comida muy picante y bebidas muy calientes' },
        { kind: 'p', text: 'Ambas pueden desatar un sofoco al subir tu temperatura corporal. Si tienes muchos sofocos, son cosas fáciles y temporales para reducir y poner a prueba.' },
        { kind: 'pull', text: '«Esto no se trata de restricción. Se trata de notar qué alimentos te cuestan una buena noche de sueño, y decidir por ti misma.»' },
      ],
    },
    {
      id: 'sleep-hormones',
      category: 'Salud mental',
      tone: 'plum',
      title: 'Sueño, hormonas, y qué realmente ayuda.',
      lede: 'Los cambios de sueño en la perimenopausia son reales, frustrantes y solucionables. Esto es lo que está pasando.',
      readTime: '7 min de lectura',
      published: 'Febrero 2026',
      body: [
        { kind: 'p', text: 'Te despiertas a las 3 a.m. y no te puedes volver a dormir. O estás cansada pero acelerada. O te despiertas empapada. Nada de esto es tu imaginación, son tus hormonas.' },
        { kind: 'h2', text: 'Qué realmente ayuda' },
        { kind: 'ul', items: [
          'Glicinato de magnesio, 200–400 mg, 30 min antes de dormir',
          'Cuarto fresco, 18–20 °C es ideal',
          'Cafeína antes del mediodía, no a las 3 p.m.',
          'El alcohol es el mayor disruptor del sueño en mujeres 45+',
          'Entrenamiento de fuerza temprano en el día mejora la profundidad del sueño',
        ]},
        { kind: 'pull', text: '«El alcohol es el mayor disruptor del sueño en mujeres en la mediana edad. Quitarlo dos semanas es el experimento más rápido que puedes hacer.»' },
      ],
    },
    {
      id: 'strength-beginners',
      category: 'Ejercicio',
      tone: 'sage',
      title: 'Entrenamiento de fuerza cuando nunca has levantado pesas.',
      lede: 'No necesitas gimnasio, entrenador, ni equipamiento para empezar. Aquí tienes un camino para principiantes que sí funciona.',
      readTime: '6 min de lectura',
      published: 'Enero 2026',
      body: [
        { kind: 'p', text: 'El entrenamiento de fuerza es lo más importante que puedes hacer por tu cuerpo después de los 45. Protege los huesos, construye músculo, mejora el sueño. Y puedes empezar desde cero.' },
        { kind: 'h2', text: 'Un plan inicial de dos semanas' },
        { kind: 'ul', items: [
          'Día 1: 10 sentadillas, 10 lagartijas en la pared, plancha de 10 segundos. Dos rondas.',
          'Día 2: Camina 20 minutos.',
          'Día 3: Igual que el día 1, agrega una ronda más.',
          'Día 4: Descanso o caminar.',
          'Día 5: Agrega mancuernas de 2 kg (o dos latas de frijoles) a las sentadillas.',
          'Día 6–7: Repite lo que se sienta bien.',
        ]},
        { kind: 'pull', text: '«Dos sesiones cortas a la semana, cada semana, ganan a un día heroico de gimnasio al mes.»' },
      ],
    },
    {
      id: 'life-after-menopause',
      category: 'Menopausia',
      tone: 'plum',
      title: 'La vida después de la menopausia: qué cambia y qué no.',
      lede: 'La menopausia es un solo día, doce meses después de tu último periodo. Todo lo que sigue es su propio capítulo. Esto es lo que realmente cambia.',
      readTime: '6 min de lectura',
      published: 'Marzo 2026',
      body: [
        { kind: 'p', text: 'Una vez que estás en la posmenopausia, los cambios hormonales bruscos de la perimenopausia se vuelven algo más estable, bajo pero constante. Para muchas mujeres, eso ya trae alivio: menos sorpresas, más previsibilidad.' },
        { kind: 'h2', text: 'Qué suele mejorar' },
        { kind: 'ul', items: [
          'Los periodos, obviamente, terminan',
          'Los cambios de humor suelen estabilizarse',
          'Los sofocos se desvanecen para la mayoría en unos años, aunque no para todas',
        ]},
        { kind: 'h2', text: 'Qué merece atención continua' },
        { kind: 'p', text: 'El estrógeno bajo a largo plazo afecta la densidad ósea, la salud del corazón, y el tejido vaginal. Nada de esto da miedo, solo vale la pena saberlo para adelantarte con tu médico: revisión de densidad ósea, chequeos cardiovasculares, y opciones para la sequedad vaginal si aparece.' },
        { kind: 'h2', text: 'Menopausia temprana o quirúrgica' },
        { kind: 'p', text: 'Si la menopausia llegó antes de lo esperado, antes de los 45, o de repente por cirugía, las mismas consideraciones a largo plazo aplican antes. Vale la pena una conversación honesta con tu médico sobre terapia hormonal dado el periodo más largo involucrado.' },
        { kind: 'pull', text: '«La menopausia no es un final. Es un capítulo más estable, y vale la pena saber cómo cuidarlo.»' },
      ],
    },
    {
      id: 'intimacy-and-connection',
      category: 'Salud mental',
      tone: 'plum',
      title: 'Intimidad y conexión durante el cambio.',
      lede: 'El deseo, la sequedad, y la cercanía con tu pareja cambian durante esta transición. Nada de esto es motivo de vergüenza, y la mayoría se puede trabajar.',
      readTime: '6 min de lectura',
      published: 'Febrero 2026',
      body: [
        { kind: 'p', text: 'El estrógeno bajo adelgaza y reseca el tejido vaginal, lo que puede hacer el sexo incómodo o doloroso. La testosterona baja y el cansancio general de esta etapa también pueden bajar el deseo. Ambos son comunes, y ninguno tiene que ser permanente.' },
        { kind: 'h2', text: 'Qué ayuda con la sequedad y la incomodidad' },
        { kind: 'ul', items: [
          'Hidratantes vaginales (usados con regularidad, no solo antes del sexo)',
          'Lubricante de silicona o base acuosa durante la intimidad',
          'Estrógeno vaginal en dosis baja, pregunta a tu médico, es diferente a la TRH sistémica',
          'Más tiempo en el juego previo y sin prisas, la excitación suele tomar más tiempo ahora',
        ]},
        { kind: 'h2', text: 'El lado emocional' },
        { kind: 'p', text: 'Una baja en el deseo no es un veredicto sobre tu relación o tu cuerpo. Hablarlo, con tu pareja o con tu médico, suele ayudar más que quedarse callada. Muchas mujeres encuentran que la conexión se profundiza una vez que la conversación sale a la luz.' },
        { kind: 'pull', text: '«No estás rota, y no estás sola. Esta es una de las partes más comunes y menos habladas de la transición.»' },
      ],
    },
    {
      id: 'hot-flashes',
      category: 'Menopausia',
      tone: 'rose',
      title: 'La verdad sobre los sofocos.',
      lede: 'Por qué pasan, por qué se sienten diferentes a las 3 a.m., y la sorprendente lista de cosas que ayudan.',
      readTime: '5 min de lectura',
      published: 'Enero 2026',
      body: [
        { kind: 'p', text: 'Un sofoco es tu cerebro malinterpretando la temperatura de tu cuerpo. La fluctuación de estrógeno afecta el centro de termorregulación en tu hipotálamo. El resultado: tu cuerpo cree que tiene calor de más, abre los vasos sanguíneos cerca de la piel, y trata de soltar calor rápido.' },
        { kind: 'h2', text: 'Qué vale la pena probar' },
        { kind: 'ul', items: [
          'Ropa en capas y dormitorio fresco, obvio pero real',
          'Evita disparadores: vino tinto, comida picante, bebidas muy calientes',
          'Respiración pausada (4 inhalando, 6 exhalando) al primer signo de sofoco',
          'La TCC para sofocos tiene respaldo clínico',
          'Para síntomas severos, habla con tu médico sobre TRH o fezolinetant',
        ]},
      ],
    },
  ],
};

// Attach real cover photography to each article by id (applies to both languages).
const ELLA_ARTICLE_IMAGES = {
  'protein-after-45':      'assets/photos/nutrition-kitchen.jpg',
  'what-is-perimenopause': 'assets/photos/reflective.jpg',
  'foods-to-avoid':         'assets/photos/nutrition-greens.jpg',
  'sleep-hormones':        'assets/photos/calm-boho.jpg',
  'strength-beginners':    'assets/photos/exercise-situps.jpg',
  'life-after-menopause':  'assets/photos/reflective.jpg',
  'intimacy-and-connection': 'assets/photos/calm-boho.jpg',
  'hot-flashes':           'assets/photos/portrait-terrace.jpg',
};
['en', 'es'].forEach((lng) => {
  (ELLA_ARTICLES[lng] || []).forEach((a) => { a.image = ELLA_ARTICLE_IMAGES[a.id] || null; });
});

export function getArticles(lang) {
  return ELLA_ARTICLES[lang] || ELLA_ARTICLES.en;
}

export function getArticle(id, lang) {
  return getArticles(lang).find(a => a.id === id) || getArticles(lang)[0];
}

