// Simple EN/ES dictionary used throughout the kit.
// Real translations would be commissioned alongside English, not auto-translated.

export const T_DICT = {
  en: {
    nav_learn: 'Learn',
    nav_supplements: 'Supplements',
    nav_doctor: 'Ask your doctor',
    nav_quiz: 'Where am I?',
    nav_about: 'About Jessica',
    nav_hormones: 'Hormonal therapy',
    nav_cancer: 'Cancer & HPV',
    cta_start: 'Start exploring',
    cta_watch: "Watch Jessica's intro",
    eyebrow_intro: 'A NOTE FROM JESSICA',
    hero_title: 'You\u2019re not imagining it.',
    hero_sub: 'Honest, plainspoken information about menopause, nutrition, supplements, exercise, mental health, and the questions to ask your doctor. Built by a physician assistant for women who deserve answers.',
    awareness_eyebrow: 'WHERE AM I?',
    awareness_title: 'A short, gentle check-in.',
    awareness_sub: 'Five quick questions. No score, no judgment, just a clearer picture of what stage your body is in and what to read next.',
    awareness_start: 'Begin the check-in',
    pillars_eyebrow: 'WHAT WE COVER',
    pillars_title: 'Everything in one trusted place.',
    pillar_nutrition: 'Nutrition',
    pillar_nutrition_desc: 'Foods to include, protein needs during menopause, healthier swaps. No meal plans, just real information.',
    pillar_supplements: 'Supplements',
    pillar_supplements_desc: 'Omega-3, Vit D, Vit K, collagen, magnesium glycinate, fiber. What\u2019s worth taking, with links to buy.',
    pillar_exercise: 'Exercise',
    pillar_exercise_desc: 'Strength training, walking, yoga. Light weights count. Less cardio, more muscle.',
    pillar_mental: 'Mental health',
    pillar_mental_desc: 'Support groups, meetups, resource links. You\u2019re not alone, and the data backs that up.',
    pillar_skin: 'Skin care',
    pillar_skin_desc: 'What hormonal changes do to your skin, and what actually helps.',
    pillar_hormones: 'Hormonal therapy',
    pillar_hormones_desc: 'HRT options explained in plain English. No endorsements, just clarity.',
    doctor_eyebrow: 'PRINTABLE',
    doctor_title: 'Questions to bring to your next OB-GYN visit.',
    doctor_sub: 'Most doctors don\u2019t focus on menopause. This printable list helps you walk in prepared, covering perimenopause, HRT options, and how to find a menopause specialist.',
    doctor_cta: 'Download the list (PDF)',
    newsletter_title: 'Get the weekly note.',
    newsletter_sub: 'Honest, useful, never spammy.',
    newsletter_placeholder: 'you@example.com',
    newsletter_cta: 'Subscribe',
    footer_tagline: 'Women supporting women through every hormonal stage of life.',
    footer_about: 'About Jessica',
    footer_credentials: 'Credentials',
    footer_contact: 'Contact',
    footer_privacy: 'Privacy',
    quiz_q1: 'What do you know about perimenopause vs. menopause?',
    quiz_q1_a1: 'I know the difference well',
    quiz_q1_a2: 'I\u2019ve heard the terms but I\u2019m unsure',
    quiz_q1_a3: 'Honestly, not much',
    quiz_q2: 'Are you experiencing any of these symptoms?',
    quiz_q2_a1: 'Hot flashes or night sweats',
    quiz_q2_a2: 'Sleep changes or insomnia',
    quiz_q2_a3: 'Mood shifts, anxiety, or low mood',
    quiz_q2_a4: 'Brain fog or memory lapses',
    quiz_q2_a5: 'Irregular or heavy periods',
    quiz_q2_a6: 'None of the above',
    quiz_q3: 'Does thinking about these symptoms cause you stress or embarrassment?',
    quiz_q3_a1: 'Yes, a lot',
    quiz_q3_a2: 'Sometimes',
    quiz_q3_a3: 'Not really',
    quiz_back: 'Back',
    quiz_next: 'Next',
    quiz_finish: 'See what to read next',
    quiz_progress: 'Question {n} of {total}',
    article_back: 'All articles',
    article_save: 'Save',
    article_share: 'Share',
    article_reading: '8 min read',
  },
  es: {
    nav_about: 'Sobre Jessica',
    nav_learn: 'Aprende',
    nav_supplements: 'Suplementos',
    nav_doctor: 'Pregunta a tu m\u00e9dico',
    nav_quiz: '\u00bfD\u00f3nde estoy?',
    nav_hormones: 'Terapia hormonal',
    nav_cancer: 'C\u00e1ncer y VPH',
    cta_start: 'Empieza a explorar',
    cta_watch: 'Mira la introducci\u00f3n de Jessica',
    eyebrow_intro: 'UN MENSAJE DE JESSICA',
    hero_title: 'No te lo est\u00e1s imaginando.',
    hero_sub: 'Informaci\u00f3n honesta y clara sobre la menopausia, nutrici\u00f3n, suplementos, ejercicio, salud mental, y las preguntas que debes hacerle a tu m\u00e9dico. Creado por una asistente m\u00e9dica para mujeres que merecen respuestas.',
    awareness_eyebrow: '\u00bfD\u00d3NDE ESTOY?',
    awareness_title: 'Un peque\u00f1o chequeo, sin presi\u00f3n.',
    awareness_sub: 'Cinco preguntas rápidas. Sin puntaje, sin juicio, solo una imagen más clara de la etapa en la que está tu cuerpo y qué leer después.',
    awareness_start: 'Comenzar',
    pillars_eyebrow: 'LO QUE CUBRIMOS',
    pillars_title: 'Todo en un solo lugar de confianza.',
    pillar_nutrition: 'Nutrici\u00f3n',
    pillar_nutrition_desc: 'Alimentos para incluir, necesidades de prote\u00edna durante la menopausia, sustituciones m\u00e1s sanas. Sin planes de comidas, solo informaci\u00f3n real.',
    pillar_supplements: 'Suplementos',
    pillar_supplements_desc: 'Omega-3, Vit D, Vit K, col\u00e1geno, glicinato de magnesio, fibra. Qu\u00e9 vale la pena tomar, con enlaces para comprar.',
    pillar_exercise: 'Ejercicio',
    pillar_exercise_desc: 'Entrenamiento de fuerza, caminar, yoga. Las pesas ligeras cuentan. Menos cardio, m\u00e1s m\u00fasculo.',
    pillar_mental: 'Salud mental',
    pillar_mental_desc: 'Grupos de apoyo, reuniones, recursos. No est\u00e1s sola, y los datos lo confirman.',
    pillar_skin: 'Cuidado de la piel',
    pillar_skin_desc: 'Qu\u00e9 le hacen los cambios hormonales a tu piel, y qu\u00e9 realmente ayuda.',
    pillar_hormones: 'Terapia hormonal',
    pillar_hormones_desc: 'Las opciones de TRH explicadas con claridad. Sin recomendaciones, solo informaci\u00f3n.',
    doctor_eyebrow: 'IMPRIMIBLE',
    doctor_title: 'Preguntas para tu pr\u00f3xima cita ginecol\u00f3gica.',
    doctor_sub: 'La mayor\u00eda de los m\u00e9dicos no se enfocan en la menopausia. Esta lista imprimible te ayuda a llegar preparada, cubre la perimenopausia, opciones de TRH, y c\u00f3mo encontrar un especialista en menopausia.',
    doctor_cta: 'Descargar la lista (PDF)',
    newsletter_title: 'Recibe la nota semanal.',
    newsletter_sub: 'Honesta, \u00fatil, nunca spam.',
    newsletter_placeholder: 'tu@ejemplo.com',
    newsletter_cta: 'Suscribirme',
    footer_tagline: 'Mujeres apoyando a mujeres en cada etapa hormonal de la vida.',
    footer_about: 'Sobre Jessica',
    footer_credentials: 'Credenciales',
    footer_contact: 'Contacto',
    footer_privacy: 'Privacidad',
    quiz_q1: '\u00bfQu\u00e9 sabes sobre la perimenopausia vs. la menopausia?',
    quiz_q1_a1: 'Conozco bien la diferencia',
    quiz_q1_a2: 'He o\u00eddo los t\u00e9rminos pero no estoy segura',
    quiz_q1_a3: 'Honestamente, no mucho',
    quiz_q2: '\u00bfEst\u00e1s experimentando alguno de estos s\u00edntomas?',
    quiz_q2_a1: 'Sofocos o sudores nocturnos',
    quiz_q2_a2: 'Cambios en el sue\u00f1o o insomnio',
    quiz_q2_a3: 'Cambios de humor, ansiedad o tristeza',
    quiz_q2_a4: 'Niebla mental o lapsos de memoria',
    quiz_q2_a5: 'Per\u00edodos irregulares o abundantes',
    quiz_q2_a6: 'Ninguno de los anteriores',
    quiz_q3: '\u00bfPensar en estos s\u00edntomas te causa estr\u00e9s o verg\u00fcenza?',
    quiz_q3_a1: 'S\u00ed, mucho',
    quiz_q3_a2: 'A veces',
    quiz_q3_a3: 'En realidad no',
    quiz_back: 'Atr\u00e1s',
    quiz_next: 'Siguiente',
    quiz_finish: 'Ver qu\u00e9 leer despu\u00e9s',
    quiz_progress: 'Pregunta {n} de {total}',
    article_back: 'Todos los art\u00edculos',
    article_save: 'Guardar',
    article_share: 'Compartir',
    article_reading: '8 min de lectura',
  },
};


export function makeT(lang) {
  return (key, vars) => {
    let s = (T_DICT[lang] && T_DICT[lang][key]) || T_DICT.en[key] || key;
    if (vars) for (const k in vars) s = s.replace("{" + k + "}", vars[k]);
    return s;
  };
}
